import IdealistaScraper

# zone information
zones = ["Santo António",
"Avenidas Novas",
"Estrela",
"Av. da Liberdade - Marquês de Pombal, Santo António",
"Misericórdia",
"Alcântara",
"Arroios",
"Alcântara, Estrela",
"Belém",
"São Jorge de Arroios, Arroios",
"Lumiar",
"Santa Maria Maior",
"Campo de Ourique",
"Campo Pequeno - Praça de Espanha, Avenidas Novas",
"Campolide",
"Centro - Nova Campolide, Campolide",
"Alvalade",
"Junqueira, Alcântara",
"Saldanha - Picoas, São Jorge de Arroios",
"Campo de Santana - Santa Marta, Santo António",
"Campo Grande, Alvalade",
"Centro, Belém",
"Marvila",
"Olivais",
"Alto de Santo Amaro, Alcântara",
"Alto do Lumiar - Quinta das Conchas - Quinta do Lambert, Lumiar",
"Parque das Nações",
"Principe Real - Praça da Alegria, Santo António",
"Areeiro",
"Cais do Sodré - Santos, Misericórdia",
"Expo Central, Parque das Nações",
"Entrecampos, Avenidas Novas",
"Alfama - Sé, Santa Maria Maior",
"Bairro Alto, Misericórdia",
"Restelo, Belém",
"Ajuda",
"Bairro Azul - Parque Eduardo VII, Avenidas Novas",
"Baixa, Santa Maria Maior",
"Beato",
"Chiado - Pç. de Camões, Misericórdia",
"Estefânia, São Jorge de Arroios",
"Largo do Rato - Estrela, Campo de Ourique",
"Quinta dos Alcoutins, Lumiar",
"São Vicente",
"Amoreiras, Campo de Ourique",
"Benfica",
"Bica - Santa Catarina, Misericórdia",
"Calçada da Ajuda - Belém, Ajuda",
"Carnide",
"Castelo - Mouraria, Santa Maria Maior",
"Centro, Campo de Ourique",
"Pena, Arroios",
"Portas de Benfica - Mercado de Benfica, Benfica",
"Santos-o-Velho - Madragoa, Estrela",
"São Domingos de Benfica",
"Alto dos Moinhos, São Domingos de Benfica",
"Anjos, Arroios",
"Graça, São Vicente",
"Príncipe Real - São Bento, Misericórdia",
"Rossio - Martim Moniz, Santa Maria Maior",
"Santa Clara",
"Santa Isabel, Campo de Ourique",
"São Sebastião da Pedreira, Avenidas Novas",
"São Vicente de Fora, São Vicente",
"Torre de Belém, Belém",
"Caramão da Ajuda, Ajuda",
"Carriche - Hospital das Forças Armadas, Lumiar",
"Centro, Penha de França",
"Centro, Lumiar",
"Expo Sul, Parque das Nações",
"Lapa, Estrela",
"Largo do Calvário - Lx Factory, Alcântara",
"Penha de França",
"Prazeres, Estrela",
"Prazeres - Maria Pia, Campo de Ourique",
"Rato - Amoreiras, Santo António",
"São João de Brito, Alvalade",
"Sete Rios, São Domingos de Benfica",
"Alameda - Praça do Chile - Almirante Reis, São Jorge de Arroios",
"Alto da Ajuda, Ajuda",
"Alto de São João - Alto do Varejão, Penha de França",
"Alvalade",
"Alvito - Quinta do Jacinto, Alcântara",
"Arneiros, Benfica",
"Avenida do Uruguai, Benfica",
"Bairro Calçada dos Mestres, Campolide",
"Bairro da Serafina, Campolide",
"Bairro de Santa Cruz, Benfica",
"Bairro dos Actores - Barão Sabrosa, Penha de França",
"Boa Hora, Ajuda",
"Calçada do Tojal, Benfica",
"Caselas, Belém",
"Centro, Ajuda",
"Charquinho, Benfica",
"Chiado, Santa Maria Maior",
"Estrada de Benfica, São Domingos de Benfica",
"Expo Norte, Parque das Nações",
"Fonte Nova - Calhariz, Benfica",
"Gare do Oriente - Zona Sul, Parque das Nações",
"Igreja de Benfica, Benfica",
"Laranjeiras, São Domingos de Benfica",
"Paço do Lumiar, Lumiar",
"Palácio da Ajuda, Ajuda",
"Pedralvas, Benfica",
"Pedrouços, Belém",
"Praça de Espanha - Sete Rios, Campolide",
"Rio Seco - Casalinho, Ajuda",
"Santa Apolónia - Cruz da Pedra, Penha de França",
"Santa Engrácia, São Vicente",
"Telheiras, Lumiar",
]

print(type(zones))